services:

  pgm_app:
    image: php:8.4-apache
    container_name: pgm_app
    working_dir: /var/www/html
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    networks:
      - mynetwork
    command: >
      sh -c "
        apt-get update -q && apt-get install -y libpq-dev libsqlite3-dev unzip zip git -q &&
        docker-php-ext-install pdo pdo_pgsql pdo_sqlite &&
        a2enmod rewrite &&
        sed -ri 's!/var/www/html!/var/www/html/public!g' /etc/apache2/sites-available/000-default.conf /etc/apache2/apache2.conf &&
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
        composer install --no-dev --optimize-autoloader &&
        mkdir -p /var/www/html/storage/twig_cache &&
        chown -R www-data:www-data /var/www/html/storage &&
        apache2-foreground
      "

networks:
  mynetwork:
    external: true
